on: pull_request_target

jobs:
  welcome1:
    runs-on: [self-hosted, x64, sten-laptop]
    steps:
      - name: Check if merge to main then build and publish
        run: |
          yarn >> yarn vitest run --coverage --silent > coverage.txt & yarn vitest run --coverage --silent --outputFile testresult.json --reporter=json
      - uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })
            const fs = require('fs');
            const coverage_table = await fs.readFileSync('coverage.txt',"utf8");
            const testresults = JSON.parse(await fs.readFileSync('testresult.json',"utf8"));
            const regex = /.*\n=+/s;
            const replacedText = coverage_table.replace(regex, '');
            
            let sendstring = `
            # Tests
            - ${testresults.numPassedTests}/${testresults.numTotalTests}
            - success:${testresults.success}
            # Test coverage
            ${replacedText}
            `
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: sendstring
            })
