on: pull_request_target

jobs:
  welcome1:
    runs-on: [self-hosted, x64, sten-laptop]
    steps:
      - name: Check if merge to main then build and publish
        run: |
          yarn
          echo '```' > coverage.txt
          yarn vitest run --coverage --silent >> coverage.txt
          echo '```' >> coverage.txt
          curl -s -H "Authorization: token ${secrets.TOKEN}" \
          -X POST -d '{"body": "Your Message to Comment"}' \
          "https://api.github.com/repos/sten-henriksson/preact-vitest-vite/issues/${github.event.number}/comments"
