name: Add text file content as comment on merge request
on:
  pull_request:
    types: [opened]

jobs:
  add_comment:
    runs-on: [self-hosted, x64, sten-laptop]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read text file content
        uses: actions/github-script@v4
        id: get_file_content
        with:
          script: |
            const fs = require('fs');
            const fileContent = fs.readFileSync('./testtext.txt', 'utf8');
            return {
              fileContent: fileContent,
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add comment to pull request
        uses: actions/github-script@v4
        with:
          script: |
            const { data: comment } = await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${
                context.payload.pull_request.user.login
              } opened a pull request and the content of the text file is: ${
                github.context.payload.get_file_content.fileContent
              }`,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
