on: pull_request_target

jobs:
  welcome1:
    runs-on: [self-hosted, x64, sten-laptop]
    steps:
      - name: Check if merge to main then build and publish
        if: github.event.pull_request.base.ref == 'main'
        run: |
          yarn
          yarn vitest run --silent --coverage > coverage.txt
          echo ls
          cat coverage.txt
  welcome:
    runs-on: [self-hosted, x64, sten-laptop]
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination
            const creator = context.payload.sender.login
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })
            const fs = require('fs');
            const fileContent = fs.readFileSync('./coverage.txt', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fileContent
            })
 